### ISSUE TITLE
Issue while installation of product_pack

### ISSUE THREAD

**Issue by ajinkyagadewar** [ingadhoc/product#118]
Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/http.py", line 641, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/odoo-server/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/odoo/odoo-server/odoo/http.py", line 333, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/odoo-server/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/odoo-server/odoo/http.py", line 326, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 506, in response_wrap
    response = f(*args, **kw)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 890, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 882, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/odoo/odoo-server/odoo/models.py", line 5494, in onchange
    record._onchange_eval(name, field_onchange[name], result)
  File "/odoo/odoo-server/odoo/models.py", line 5392, in _onchange_eval
    method_res = method(self)
  File "/odoo/odoo-server/addons/sale_stock/models/sale_order.py", line 133, in _onchange_product_id_uom_check_availability
    self._onchange_product_id_check_availability()
  File "/odoo/odoo-server/addons/sale_stock/models/sale_order.py", line 143, in _onchange_product_id_check_availability
    if float_compare(self.product_id.virtual_available, product_qty, precision_digits=precision) == -1:
  File "/odoo/odoo-server/odoo/fields.py", line 910, in __get__
    self.determine_value(record)
  File "/odoo/odoo-server/odoo/fields.py", line 1022, in determine_value
    self.compute_value(recs)
  File "/odoo/odoo-server/odoo/fields.py", line 976, in compute_value
    self._compute_value(records)
  File "/odoo/odoo-server/odoo/fields.py", line 967, in _compute_value
    getattr(records, self.compute)()
  File "/odoo/product-extra/product_pack/models/product.py", line 35, in _compute_quantities
    subproduct_stock = res[subproduct.product_id.id]
TypeError: 'NoneType' object has no attribute '__getitem__'

**Comment by ajinkyagadewar** [comment]
Sorry not while installation but after selection of the product in Sales Order
