### ISSUE TITLE
[12.0] Server error al entrar a ventas

### ISSUE THREAD

**Issue by FedericoLaTorre** [ingadhoc/product#311]
Odoo 12, ubuntu 18.04. Server error al tratar de ingresar a ventas

Error:
Odoo Server Error

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 1049, in get
    value = self._data[key][field][record._ids[0]]
KeyError: 349

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1005, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 1051, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: ('sale.order(349,).expected_date', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 1049, in get
    value = self._data[key][field][record._ids[0]]
KeyError: 780

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1005, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 1051, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: ('sale.order.line(780,).state', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 98, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 904, in search_read
    return self.do_search_read(model, fields, offset, limit, domain, sort)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 926, in do_search_read
    offset=offset or 0, limit=limit or False, order=sort or False)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 4612, in search_read
    result = records.read(fields)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 2815, in read
    vals[name] = convert(record[name], record, use_name_get)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 5143, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1009, in __get__
    self.determine_value(record)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1122, in determine_value
    self.compute_value(recs)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1076, in compute_value
    self._compute_value(records)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1067, in _compute_value
    getattr(records, self.compute)()
  File "/usr/lib/python3/dist-packages/odoo/addons/sale_stock/models/sale_order.py", line 48, in _compute_expected_date
    super(SaleOrder, self)._compute_expected_date()
  File "/usr/lib/python3/dist-packages/odoo/addons/sale/models/sale.py", line 247, in _compute_expected_date
    for line in order.order_line.filtered(lambda x: x.state != 'cancel' and not x._is_delivery()):
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 4921, in filtered
    return self.browse([rec.id for rec in self if func(rec)])
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 4921, in <listcomp>
    return self.browse([rec.id for rec in self if func(rec)])
  File "/usr/lib/python3/dist-packages/odoo/addons/sale/models/sale.py", line 247, in <lambda>
    for line in order.order_line.filtered(lambda x: x.state != 'cancel' and not x._is_delivery()):
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1009, in __get__
    self.determine_value(record)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1112, in determine_value
    record._prefetch_field(self)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 2860, in _prefetch_field
    result = records.read([f.name for f in fs], load='_classic_write')
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 2798, in read
    self._read_from_database(stored, inherited)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 2925, in _read_from_database
    cr.execute(query_str, params)
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 148, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 225, in execute
    res = self._obj.execute(query, params)
psycopg2.ProgrammingError: column sale_order_line.pack_modifiable does not exist
LINE 1: ..."sequence","sale_order_line"."lot_id" as "lot_id","sale_orde...
                                                             ^

**Comment by FedericoLaTorre** [comment]
Se soluciona desinstalando y reinstalando el modulo "sale order line number".

**Comment by sotolucas** [comment]
Gracias por la info Federico.
Saludos!
